-- JSON flattener audit log: one row per VIEW SQL generated by generate_json_flattener().
--
-- Stores the generated BigQuery VIEW DDL so operators can audit what the agent
-- proposed, replay a deployment, or compare across iterations.  `deployed` is
-- set to TRUE by the agent after the corresponding create_transformation MCP call
-- succeeds; FALSE / NULL means the VIEW was generated but not yet deployed.
--
-- Append-only — rows are never updated after insert.  If the agent regenerates
-- a VIEW for the same column, a new row is written (incrementing history).

CREATE TABLE IF NOT EXISTS `agent_state.json_flattener_log` (
  log_id        STRING    NOT NULL,   -- UUID, dedup key
  connection_id STRING    NOT NULL,
  table_name    STRING    NOT NULL,   -- source table containing the JSON column
  column_name   STRING    NOT NULL,   -- name of the JSON/semi-structured column
  view_name     STRING    NOT NULL,   -- proposed BQ view name (dataset.table_flat)
  view_sql      STRING    NOT NULL,   -- full CREATE OR REPLACE VIEW DDL
  generated_at  TIMESTAMP NOT NULL,
  deployed      BOOL                  -- NULL = not yet attempted
)
PARTITION BY DATE(generated_at)
CLUSTER BY connection_id;
